### ISSUE TITLE
Doesn't seem to work on large files?

### ISSUE THREAD

**Issue by Timmmm** [evestera/json_typegen#37]
I have a 130 MB JSON file (from `llvm-tblgen --dump-json`) but unfortunately it just seems to freeze when I run it through `json_typegen`. I don't even get a progress bar (which I think the CLI is supposed to do?)

Any hints on how to debug this?

**Comment by Timmmm** [comment]
Huh it didn't work with the `cargo install json_typegen` version, but I tried compiling from `master` and it worked perfectly (and showed a progress bar!).

Maybe worth a new release?

**Comment by evestera** [comment]
> Maybe worth a new release?

Oh, for sure. 😬 Thank you for the reminder. I've held off doing a release due to the master branch having a bit of a regression in terms of not being able to "singularize" well when coming up with names for types, but at this point I should probably just ship with that regression and revisit that when I have time.
