### ISSUE TITLE
{"TRY": 10} parsing throws "found reserved keyword `try`"

### ISSUE THREAD

**Issue by benjaminmcdonald** [evestera/json_typegen#6]
{"TRY": 10} parsing throws "found reserved keyword `try`"

**Comment by evestera** [comment]
Ah, yes, I have to update the [list of Rust keywords](https://github.com/evestera/json_typegen/blob/master/json_typegen_shared/src/generation/rust.rs#L128) with the new ones from Rust 2018(`async`, `await` and `try`). Thank you for the issue/reminder. 👍

Will try to get it fixed in a few days (but going away for the weekend, so monday at the earliest).

**Comment by evestera** [comment]
Just released a bugfix release ([v0.3.1](https://github.com/evestera/json_typegen/releases/tag/v0.3.1)) which should fix the issue. Thanks again for the issue.
